baseURL = "/"
languageCode = "en-us"
title = "Vireframe"

theme = "hugo-vireframe"

SectionPagesMenu = "main"

[params.bulmaswatch]
  # `cdn` or `path/to/bulmaswatch.css` relative to `staticDir` configuration.
  lib = "css/bulmaswatch.min.css"
  # Bulmaswatch theme name. You can leave it blank if you don't use CDN.
  theme = "spacelab"

[params]
  # Enable global navbar or not.
  navbar = true
  # Modifier class to add to global navbar
  navbarClass = "is-black"
  # If enabled, automatically include content of `_script.html` for each page in current section.
  contentScript = true
  # Generate navbar links and sidebar (if enabled) from given menu entry.
  # Useful when paired with `sectionPagesMenu` configuration
  generateMenu = "main"
